server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/



spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
#      default-filters:
#        - TokenRelay

      routes:
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/chat/**, /api/v1/chatroom/**

        - id: ws-message-service
          uri: lb:ws://message-service
          predicates:
            - Path=/chat/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/member/**

