spring:

  application:
    name: "user-service"

  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: chat
    password: chat
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: "10b1c60213f53f6a83a0c4e48f59d5b2f80a4c3da5e38c49d96bacf9014dff6a"

